<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->head_info['title']; ?></title>
        <meta charset="utf-8" />
        <?php if (!empty($this->head_info['meta_description'])) { ?>
            <meta name="description" content="<?= $this->head_info['meta_description']; ?>" />
        <?php } ?>
        <?php if (!empty($this->head_info['meta_keywords'])) { ?>
            <meta name="keywords" content="<?= $this->head_info['meta_keywords']; ?>" />
        <?php } ?>

        <?php if (!empty($this->head_info['canonical'])) { ?>
            <link rel="canonical" href="<?php echo $this->head_info['canonical']; ?>" />
        <?php } ?>

        <link rel="stylesheet" type="text/css" href="/admn/css/style.css" />
        <script type="text/javascript" src="/admn/js/main.js"></script>

        <script type="text/javascript" src="/plugins/jquery/jquery-1.8.3.js"></script>
        <script type="text/javascript" src="/plugins/ckeditor/ckeditor.js"></script>

    </head>
    <body>
        <div id="container">
            <div id="header_outer">
                <div id="header_inner">
                    <h1>Portfolio - Glenn Blom</h1>
                    <div id="nav">
                        <?php echo $this->navigation(); ?>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <div id="content_outer">
                <div id="content_inner">
                    <?php if ($this->errorMsg != '') { ?>
                        <div id="error"><?php echo $this->errorMsg; ?></div>
                    <?php } ?>
                    <?= $this->layout()->content; ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </body>
</html>