<div id="title_outer">
    <div id="title_inner">
        <h1>Projecten</h1>
    </div>
</div>
<div id="content_inner">
    <div class="projects">
        <?php
        $i = 0;
        foreach ($this->projects as $project) {
            ?>
            <div class="project">
                <a href="/projecten<?php echo $project->canonical; ?>">
                    <img src="/img/projects/<?php echo $project->img; ?>" alt="<?php echo $project->title; ?>" title="<?php echo $project->title; ?>" />
                    <h2><?php echo $project->title; ?></h2>
                    <p><?php echo nl2br($project->meta_descr); ?></p>
                </a>
                <a href="/projecten<?php echo $project->canonical; ?>" class="button">Lees meer</a>
            </div>
            <?php
            if ($i == 2) {
                echo '<div class="clear"></div>';
            }
            $i++;
        }
        ?>
        <div class="clear"></div>
        <?php
        if (is_array($this->prevPages)) {
            echo '<div class="prev">';
            $first = true;
            foreach ($this->prevPages as $page) {
                if ($first) {
                    echo '<a href="' . $page['url'] . '">' . $page['name'] . '</a>';
                    $first = false;
                } else {
                    echo ' | <a href="' . $page['url'] . '">' . $page['name'] . '</a>';
                }
            }
            echo '</div>';
        }
        
        if (is_array($this->nextPages)) {
            echo '<div class="next">';
            $first = true;
            foreach ($this->nextPages as $page) {
                if ($first) {
                    echo '<a href="' . $page['url'] . '">' . $page['name'] . '</a>';
                    $first = false;
                } else {
                    echo ' | <a href="' . $page['url'] . '">' . $page['name'] . '</a>';
                }
            }
            echo '</div>';
        }
        
        if (is_array($this->pages)) {
            echo '<div class="pages">';
            $first = true;
            foreach ($this->pages as $page) {
                if ($first) {
                    if ($page['name'] != $this->currentPage) {
                        echo '<a href="' . $page['url'] . '">' . $page['name'] . '</a>';
                    } else {
                        echo '<strong><u>' . $page['name'] . '</u></strong>';
                    }
                    $first = false;
                } else {
                    if ($page['name'] != $this->currentPage) {
                        echo ' | <a href="' . $page['url'] . '">' . $page['name'] . '</a>';
                    } else {
                        echo ' | <strong><u>' . $page['name'] . '</u></strong>';
                    }
                }
            }
            echo '</div>';
        }
        ?>
        <div class="clear"></div>
    </div>
</div>