<div id="title_outer">
    <div id="title_inner">
        <h1><?= $this->projectinfo->title; ?></h1>
    </div>
</div>
<div id="content_inner">
    <div id="left_column">
        <?= $this->leftColNav; ?>
    </div>
    <div id="right_column">
        <a href="/img/projects/<?= $this->projectinfo->img; ?>" class="lightbox">
            <img src="/img/projects/<?= $this->projectinfo->img; ?>" alt="<?= $this->projectinfo->title; ?>" title="<?= $this->projectinfo->title; ?>" class="main" />
        </a>
        <script type="text/javascript">
            $(function() {
                $('a.lightbox').lightBox();
            });
        </script>
        <?= $this->projectinfo->descr; ?>
    </div>
</div>