<div id="title_outer">
    <div id="title_inner">
        <h1><?= $this->projectinfo->title; ?></h1>
    </div>
</div>
<div id="content_inner">
    <div id="left_column">
        <?= $this->leftColNav; ?>
    </div>
    <div id="right_column">
        <img src="/img/projects/<?= $this->projectinfo->img; ?>" alt="<?= $this->projectinfo->title; ?>" title="<?= $this->projectinfo->title; ?>" class="main" />
        <?= $this->projectinfo->descr; ?>
    </div>
</div>