<div id="slider_outer">
    <div id="slider_inner">

        <!-- Start WOWSlider.com BODY section -->
        <div id="wowslider-container1">
            <div class="ws_images"><ul>
                    <li><a href="http://portfolio-prj2.glennblom.nl/img/pc/slider/cheapestconsoles1.png" target="_blank"><img src="img/pc/slider/cheapestconsoles1.png" alt="Cheapest Consoles" title="Cheapest Consoles" id="wows1_0"/></a></li>
                    <li><a href="http://portfolio-prj2.glennblom.nl/img/pc/slider/dehaarfabriek1.png" target="_blank"><img src="img/pc/slider/dehaarfabriek1.png" alt="Dehaarfabriek" title="Dehaarfabriek" id="wows1_1"/></a></li>
                    <li><a href="http://portfolio-prj2.glennblom.nl/img/pc/slider/portfolio.png" target="_blank"><img src="img/pc/slider/portfolio1.png" alt="Portfolio" title="Portfolio" id="wows1_2"/></a></li>
                </ul></div>
            <div class="ws_bullets"><div>
                    <a href="#" title="cheapestconsoles1"><img src="img/pc/slider/cheapestconsoles1.png" alt="Cheapest Consoles"/>1</a>
                    <a href="#" title="dehaarfabriek1"><img src="img/pc/slider/dehaarfabriek1.png" alt="Dehaarfabriek"/>2</a>
                    <a href="#" title="portfolio1"><img src="img/pc/slider/portfolio1.png" alt="Portfolio"/>3</a>
                </div></div>
            <a class="wsl" href="http://wowslider.com">Slideshow Software by WOWSlider.com v2.7.1</a>
            <div class="ws_shadow"></div>
        </div>
        <script type="text/javascript" src="js/slider/wowslider.js"></script>
        <script type="text/javascript" src="js/slider/script.js"></script>
        <!-- End WOWSlider.com BODY section -->

    </div>
</div>
<div id="content_inner">
    <div>
        <h2>Titel</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mi, commodo vel dignissim a, placerat a felis. In euismod fringilla porttitor. Maecenas sed nibh id mi luctus consequat quis nec sem. Sed venenatis eleifend neque, ac pellentesque odio convallis et. Nulla mollis sem sit amet purus sodales nec gravida dolor venenatis. Maecenas lobortis erat non nisi tempus egestas. Fusce sed diam at tellus accumsan pharetra.</p>
    </div>
    <div>
        <h2>Titel</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mi, commodo vel dignissim a, placerat a felis. In euismod fringilla porttitor. Maecenas sed nibh id mi luctus consequat quis nec sem. Sed venenatis eleifend neque, ac pellentesque odio convallis et. Nulla mollis sem sit amet purus sodales nec gravida dolor venenatis. Maecenas lobortis erat non nisi tempus egestas. Fusce sed diam at tellus accumsan pharetra.</p>
    </div>
    <div>
        <h2>Titel</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mi, commodo vel dignissim a, placerat a felis. In euismod fringilla porttitor. Maecenas sed nibh id mi luctus consequat quis nec sem. Sed venenatis eleifend neque, ac pellentesque odio convallis et. Nulla mollis sem sit amet purus sodales nec gravida dolor venenatis. Maecenas lobortis erat non nisi tempus egestas. Fusce sed diam at tellus accumsan pharetra.</p>
    </div>
</div>