<div id="slider_outer">
    <div id="slider_inner">
        <?
        foreach ($this->slideshow as $slide) {
            ?>
            <div class="slide" style="display: none;">
                <div class="slide_img" style="float: <?= $slide['img_loc']; ?>">
                    <a href="<?= $slide['url']; ?>">
                        <img src="/img/slideshow/<?= $slide['img']; ?>" alt="<?= $slide['title']; ?>" title="<?= $slide['title']; ?>" />
                    </a>
                </div>
                <div class="slide_content" style="<?= 'padding-' . $slide['img_loc'] . ': 20px;'; ?>">
                    <h2><?= $slide['title']; ?></h2>
                    <p><?= $slide['descr']; ?></p>
                    <a href="<?= $slide['url']; ?>" class="button">Lees meer</a>
                </div>
                <div class="clear"></div>
            </div>
            <?
        }
        ?>
    </div>
    <div id="slideNumbers"></div>
    <script type="text/javascript">
        $('#slider_inner')
        .cycle({
            fx: 'fade',
            speed: 1500,
            timeout: 4500,
            pause: 1,
            pager: '#slideNumbers'
        });
    </script>
</div>

<div id="content_inner">
    <? foreach ($this->textBlocks as $textBlock) { ?>
    <div class="text_block">
        <h2><?= $textBlock->title; ?></h2>
        <?= $textBlock->descr; ?>
        <a class="button" href="<?= $textBlock->url; ?>">Lees meer</a>
    </div>
    <? } ?>
</div>