<div id="slider_outer">
    <div id="slider_inner">
        <?php
        foreach ($this->slideshow as $slide) {
            ?>
            <div class="slide" style="display: none;">
                <div class="slide_img" style="float: <?= $slide['img_loc']; ?>">
                    <a href="<?= $slide['url']; ?>">
                        <img src="/img/slideshow/<?= $slide['img']; ?>" alt="<?= $slide['title']; ?>" title="<?= $slide['title']; ?>" />
                    </a>
                </div>
                <div class="slide_content" style="<?= 'padding-' . $slide['img_loc'] . ': 20px;'; ?>">
                    <h2><?= $slide['title']; ?></h2>
                    <p><?= $slide['descr']; ?></p>
                    <a href="<?= $slide['url']; ?>" class="button">Lees meer</a>
                </div>
                <div class="clear"></div>
            </div>
            <?php
        }
        ?>
    </div>
    <div id="slideNumbers"></div>
    <script type="text/javascript">
        $('#slider_inner')
        .cycle({
            fx: 'fade',
            speed: 1500,
            timeout: 4500,
            pause: 1,
            pager: '#slideNumbers'
        });
    </script>
</div>

<div id="content_inner">
    <div class="box">
        <h2>Titel</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mi, commodo vel dignissim a, placerat a felis. In euismod fringilla porttitor. Maecenas sed nibh id mi luctus consequat quis nec sem. Sed venenatis eleifend neque, ac pellentesque odio convallis et. Nulla mollis sem sit amet purus sodales nec gravida dolor venenatis. Maecenas lobortis erat non nisi tempus egestas. Fusce sed diam at tellus accumsan pharetra.</p>
    </div>
    <div class="box">
        <h2>Titel</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mi, commodo vel dignissim a, placerat a felis. In euismod fringilla porttitor. Maecenas sed nibh id mi luctus consequat quis nec sem. Sed venenatis eleifend neque, ac pellentesque odio convallis et. Nulla mollis sem sit amet purus sodales nec gravida dolor venenatis. Maecenas lobortis erat non nisi tempus egestas. Fusce sed diam at tellus accumsan pharetra.</p>
    </div>
    <div class="box">
        <h2>Titel</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur justo mi, commodo vel dignissim a, placerat a felis. In euismod fringilla porttitor. Maecenas sed nibh id mi luctus consequat quis nec sem. Sed venenatis eleifend neque, ac pellentesque odio convallis et. Nulla mollis sem sit amet purus sodales nec gravida dolor venenatis. Maecenas lobortis erat non nisi tempus egestas. Fusce sed diam at tellus accumsan pharetra.</p>
    </div>
</div>