<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->head_info['title']; ?></title>
        <meta charset="utf-8" />
        <? if (!empty($this->head_info['meta_description'])) { ?>
            <meta name="description" content="<?= $this->head_info['meta_description']; ?>" />
        <? } ?>
        <? if (!empty($this->head_info['meta_keywords'])) { ?>
            <meta name="keywords" content="<?= $this->head_info['meta_keywords']; ?>" />
        <? } ?>

        <? if (!empty($this->head_info['canonical'])) { ?>
            <link rel="canonical" href="<?= $this->head_info['canonical']; ?>" />
        <? } ?>

        <link rel="stylesheet" type="text/css" href="/webmaster-panel/css/style.css" />
        <script type="text/javascript" src="/webmaster-panel/js/main.js"></script>

        <script type="text/javascript" src="/plugins/jquery/jquery-1.8.3.js"></script>
        <script type="text/javascript" src="/plugins/ckeditor/ckeditor.js"></script>

    </head>
    <body>
        <div id="container">
            <div id="header_outer">
                <div id="header_inner">
                    <p>Portfolio - Glenn Blom</p>
                    <div id="nav">
                        <?= $this->navigation(); ?>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <div id="content_outer">
                <? if ($this->errorMsg != '') { ?>
                    <div id="error"><?= $this->errorMsg; ?></div>
                <? } ?>
                <?= $this->layout()->content; ?>
                <div class="clear"></div>
            </div>
        </div>
    </body>
</html>