<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headMeta(); ?>


        <?php echo $this->headLink()->appendStylesheet('/css/style.css'); ?>


        <?php
        echo $this->headScript()->appendFile('/plugins/jquery/jquery-1.8.3.js')
                ->appendFile('/plugins/jquery/jquery.cycle.all.js')
                ->appendFile('/js/main.js');
        ?>

    </head>
    <body>
        <div id="container">
            <div id="header_outer">
                <div id="header_inner">
                    <h1>Portfolio - Glenn Blom</h1>
                    <div id="nav">
                        <?php echo $this->navigation(); ?>
                    </div>
                    <div id="search">
                        <?= $this->searchForm; ?>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <div id="content_outer">
                <?= $this->layout()->content; ?>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div id="footer_outer">
                <div id="footer_inner">
                    <div>
                        <h3>Projecten</h3>
                        <ul>
                            <li>
                                <a href="#">Portfolio Zend Framework</a>
                            </li>
                            <li>
                                <a href="#">Buckaroo koppeling</a>
                            </li>
                            <li>
                                <a href="#">PostNL Checkpay koppeling</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <h3>Social media</h3>
                        <ul class="social-media">
                            <li>
                                <a href="https://github.com/glenn1001/" target="_blank">
                                    <img src="/img/social-media/github.ico" alt="GitHub" title="GitHub" />
                                    GitHub
                                </a>
                            </li>
                            <li>
                                <a href="http://www.linkedin.com/profile/view?id=74647824&trk=tab_pro" target="_blank">
                                    <img src="/img/social-media/linkedin.ico" alt="LinkedIn" title="LinkedIn" />
                                    LinkedIn
                                </a>
                            </li>
                            <li>
                                <a href="http://www.facebook.com/glenn.blom.9" target="_blank">
                                    <img src="/img/social-media/facebook.ico" alt="Facebook" title="Facebook" />
                                    Facebook
                                </a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/113906563893465330742/posts" target="_blank">
                                    <img src="/img/social-media/google+.ico" alt="Google+" title="Google+" />
                                    Google+
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/glenn10011" target="_blank">
                                    <img src="/img/social-media/twitter.ico" alt="Twitter" title="Twitter" />
                                    Twitter
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="contact">
                        <h3>Neem contact op</h3>
                        <?php echo $this->contactform; ?>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        
        <?php
        if (isset($this->contactSuccess)) {
        ?>
        <script type="text/javascript">alert('<?= $this->contactSuccess; ?>');</script>
        <?php
        }
        ?>
    </body>
</html>