<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->head_info['title']; ?></title>
        <meta charset="utf-8" />
        <?php if (!empty($this->head_info['meta_description'])) { ?>
            <meta name="description" content="<?= $this->head_info['meta_description']; ?>" />
        <?php } ?>
        <?php if (!empty($this->head_info['meta_keywords'])) { ?>
            <meta name="keywords" content="<?= $this->head_info['meta_keywords']; ?>" />
        <?php } ?>

        <?php if (!empty($this->head_info['canonical'])) { ?>
            <link rel="canonical" href="<?php echo $this->head_info['canonical']; ?>" />
        <?php } ?>

        <link rel="stylesheet" type="text/css" href="/css/pc/style.css" />
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/jquery-1.8.3.js"></script>

    </head>
    <body>
        <div id="container">
            <div id="header_outer">
                <div id="header_inner">
                    <h1>Portfolio - Glenn Blom</h1>
                    <div id="nav">
                        <ul>
                            <li>Home</li>
                            <li>Kennis &amp; vaardigheden</li>
                            <li>Projecten</li>
                            <li>Curriculum Vitae</li>
                            <li>Contact</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <div id="content_outer">
                <?= $this->layout()->content; ?>
            </div>
            <div class="clear"></div>
            <div id="footer_outer">
                <div id="footer_inner">
                    Footer
                </div>
            </div>
        </div>
    </body>
</html>