<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headMeta(); ?>


        <?php echo $this->headLink()->appendStylesheet('/css/pc/style.css'); ?>


        <?php
        echo $this->headScript()->appendFile('/js/main.js')
                ->appendFile('/js/jquery-1.8.3.js');
        ?>


        <!-- Start WOWSlider.com HEAD section -->
        <link rel="stylesheet" type="text/css" href="/css/pc/slider/style.css" />
        <script type="text/javascript" src="/js/slider/jquery.js"></script>
        <!-- End WOWSlider.com HEAD section -->
    </head>
    <body>
        <div id="container">
            <div id="header_outer">
                <div id="header_inner">
                    <h1>Portfolio - Glenn Blom</h1>
                    <div id="nav">
                        <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="/kennis-vaardigheden/">Kennis &amp; vaardigheden</a></li>
                            <li>Projecten</li>
                            <li>Curriculum Vitae</li>
                            <li>Contact</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
            <div id="content_outer">
                <?= $this->layout()->content; ?>
            </div>
            <div class="clear"></div>
            <div id="footer_outer">
                <div id="footer_inner">
                    Footer
                </div>
            </div>
        </div>
    </body>
</html>