<form id="pages" method="post" action="/webmaster-panel/page/update/">
    <table>
        <tr>
            <td>&nbsp;</td>
            <td>Position</td>
            <td style="min-width: 120px;">Page</td>
            <td style="min-width: 300px;">Path</td>
            <td>Status</td>
            <td>Show in navigation</td>
            <td style="min-width: 145px;">Example</td>
        </tr>
        <?
        if (isset($this->pages[0])){
            foreach ($this->pages as $page) {
            ?>
            <tr>
                <td><input type="checkbox" name="delete[<?= $page->id; ?>]" value="Y" /></td>
                <td><input type="text" size="1" name="update[<?= $page->id; ?>]" value="<?= $page->pos; ?>" /></td>
                <td><a href="<?= $this->url(array('action' => 'edit', 'id' => $page->id)); ?>/"><?= $page->title; ?></a></td>
                <td><?= $page->path; ?></td>
                <td>
                    <select name="status[<?= $page->id; ?>]">
                        <option <? if ($page->status == 'Y'){echo 'selected="selected"';} ?> value="Y">Active</option>
                        <option <? if ($page->status == 'N'){echo 'selected="selected"';} ?>value="N">Inactive</option>
                    </select>
                </td>
                <td>
                    <select name="menu[<?= $page->id; ?>]">
                        <option <? if ($page->menu == 'Y'){echo 'selected="selected"';} ?> value="Y">Yes</option>
                        <option <? if ($page->menu == 'N'){echo 'selected="selected"';} ?>value="N">No</option>
                    </select>
                </td>
                <td><a href="<?= $page->canonical; ?>" target="_blank" class="button">View example</a></td>
            </tr>
            <?
            }
        } else {
        ?>
            <tr>
                <td>&nbsp;</td>
                <td colspan="6">There are no pages!</td>
            </tr>
        <?
        }
        ?>
    </table>
</form>
<a href="javascript: void(0);" onclick="selectAll();">Select all</a> / <a href="javascript: void(0);" onclick="deSelectAll();">Deselect all</a><br />
<button onclick="deletePages();">Delete selected</button>
<button onclick="updatePagePos();">Update all</button><br />
<a href="<?= $this->url(array('action' => 'create')); ?>/" class="button">Add new page</a>