<form id="pages" method="post" action="/webmaster-panel/page/update/">
    <table>
        <tr>
            <td>&nbsp;</td>
            <td>Position</td>
            <td style="min-width: 120px;">Page</td>
            <td style="min-width: 300px;">Path</td>
            <td>Status</td>
            <td>Show in navigation</td>
            <td style="min-width: 145px;">Example</td>
        </tr>
        <?php
        if (isset($this->pages[0])){
            foreach ($this->pages as $page) {
            ?>
            <tr>
                <td><input type="checkbox" name="delete[<?php echo $page->id; ?>]" value="Y" /></td>
                <td><input type="text" size="1" name="update[<?php echo $page->id; ?>]" value="<?php echo $page->pos; ?>" /></td>
                <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $page->id)); ?>/"><?php echo $page->title; ?></a></td>
                <td><?php echo $page->path; ?></td>
                <td>
                    <select name="status[<?php echo $page->id; ?>]">
                        <option <?php if ($page->status == 'Y'){echo 'selected="selected"';} ?> value="Y">Active</option>
                        <option <?php if ($page->status == 'N'){echo 'selected="selected"';} ?>value="N">Inactive</option>
                    </select>
                </td>
                <td>
                    <select name="menu[<?php echo $page->id; ?>]">
                        <option <?php if ($page->menu == 'Y'){echo 'selected="selected"';} ?> value="Y">Yes</option>
                        <option <?php if ($page->menu == 'N'){echo 'selected="selected"';} ?>value="N">No</option>
                    </select>
                </td>
                <td><a href="<?php echo $page->canonical; ?>" target="_blank" class="button">View example</a></td>
            </tr>
            <?php
            }
        } else {
        ?>
            <tr>
                <td>&nbsp;</td>
                <td colspan="6">There are no pages!</td>
            </tr>
        <?php
        }
        ?>
    </table>
</form>
<a href="javascript: void(0);" onclick="selectAll();">Select all</a> / <a href="javascript: void(0);" onclick="deSelectAll();">Deselect all</a><br />
<button onclick="deletePages();">Delete selected</button>
<button onclick="updatePagePos();">Update all</button><br />
<a href="<?php echo $this->url(array('action' => 'create')); ?>/" class="button">Add new page</a>